name: variables
on: push
env:
  root_env_variable: Hi
jobs:
  job1:
   runs-on: ubuntu-latest
   env:
    job_env_variable: Good Morning
   steps: 
    - name: job1
      run: echo "$root_env_variable $First_name $job_env_variable'
      env:
        First_name: user 1
  
